### PR TITLE
Updates to Teams page on website

### PR DESCRIPTION
**Pull request by bweaver-work**
Adding and shuffling current and former members.

### CODE REVIEW

**Comment by tildechris** [comment]
Daniel M's image is a bit squeezed, I wonder if cropping would help.

**Review by sgratzl — COMMENTED** [review]
changes look good. Do we have higher resolution images of the google fellows. As far as I know they are 160x160 but resized to 250x250? Moreover, do we have version without the rounded borders?

re highlight:
image

are those the one we wanna highlight?

**Comment by tildechris** [comment]
I'll follow-up with Ben on the fellows images.

> are those the one we wanna highlight?

As per Ryan, yes.

**Comment by tildechris** [comment]
I updated the Google fellows images.

> Moreover, do we have version without the rounded borders?

Which image without the rounded borders are you referring to?

**Comment by sgratzl** [comment]
> Which image without the rounded borders are you referring to?

the old google fellows images looked like: 

https://delphi.cmu.edu/about/team/images/sarah-colquhoun_head-shot_hucad583d56b035bab333b3e0bce2e9789_49177_250x250_resize_box_2.png

the new ones don't have that :+1 => can we delete the old ones then?

**Review by sgratzl — APPROVED** [review]

**Pull request merged**
