### PR TITLE
Migrate site to delphi style & existing header

### LINKED ISSUE #19: Add Delphi header
Add the Delphi header that's used in COVIDCast and the blog such that it's more obvious from the home page what the other properties are.

### PR DESCRIPTION
**Pull request by tildechris**
Closes #19 

Turns out it was easier to simply port over the styles from the blog than to try to use the header with the existing styles.

### CODE REVIEW

**Comment by tildechris** [comment]
See preview at: https://publishing.andrew.cmu.edu/collections/delphi-dev/

**Comment by capnrefsmmat** [comment]
Any chance of fixing alumni.html and bibliography.html at the same time? They also have completely different Google Analytics code that points to a different account...

**Comment by tildechris** [comment]
If it's just updating the analytics block, the sounds simple enough.  What is currently linking to bibliography?  I don't see a link to that from the home page.

**Comment by capnrefsmmat** [comment]
Not sure; I just know it's the other html file in the repo

**Comment by RoniRos** [comment]
This is awesome, Chris!   Thank you!

One small textual fix: can you please remove the two occurrences of "We are working on a new system for COVID-19." ?   They are no longer appropriate.

**Comment by tildechris** [comment]
I missed your comment about:

> One small textual fix: can you please remove the two occurrences of "We are working on a new system for COVID-19." ? They are no longer appropriate.

I'll make a new issue to fix that.

**Pull request merged**
