### PR TITLE
build: remove integrity checks

### PR DESCRIPTION
**Pull request by sgratzl**
to avoid cors error

### CODE REVIEW

**Comment by sgratzl** [comment]
@tildechris please approve cause it is important for the actual deployment since JS files won't run otherwise

**Comment by tildechris** [comment]
FYI - feel free to ping me on urgent review items on slack.  Taking a look now.

**Review by tildechris — APPROVED** [review]
LGTM.  Can you just add a short note on why this caused CORS errors?

**Comment by sgratzl** [comment]
when I go to https://cmu-delphi-main.netlify.app/blog/

I get

image

**Pull request merged**
