### PR TITLE
Migrate micromamba setup action

### PR DESCRIPTION
**Pull request by minhkhul**
This PR might fix [this problem](https://github.com/cmu-delphi/www-main/actions/runs/11039018072/job/30663544823
) thst's blocking blog build:

> Warning: This action is deprecated and no longer maintained. Please use mamba-org/setup-micromamba instead. See `[https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba`](https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba%60) for a migration guide.

### CODE REVIEW

**Comment by minhkhul** [comment]
Build time is 50 minutes with this new setup action (vs max 5 mins before). Will check for alternative way to go about this before settling.

**Comment by melange396** [comment]
looks like it worked but it took a loooong time -- almost 2h!!!  https://github.com/cmu-delphi/www-main/actions/runs/11039802772/job/30666229264

i ran it again to see if its a fluke or if it will pick up cache from the prior run: https://github.com/cmu-delphi/www-main/actions/runs/11041452519/job/30671730241

**Comment by melange396** [comment]
@minhkhul looks like our messages crossed in the night!  This action was running fairly regularly at around 13 minutes with occasional excursions...  Either way, its a large departure from before, but we should wait and see what happens with the second run.

**Comment by melange396** [comment]
The second run did not have appreciable time savings.  1.5-2h is an incredibly long time to wait for this, we should see what else we can do to speed it up.  The "Create environment" step has a lot of output that looks similar to the "Run mamba-org/setup-micromamba@v1" step, perhaps there is some repetition that can be removed?  That is probably not enough though -- even half the runtime is still much longer than the job used to take.

**Comment by minhkhul** [comment]
ye I've been looking into other options for building the blog today. I'll close this one for now.

**Comment by minhkhul** [comment]
Added caching, which is working, bringing it down to 4 min. https://github.com/cmu-delphi/www-main/actions/runs/11096551953/job/30830681257

**Pull request merged**
