### PR TITLE
simple team page

### PR DESCRIPTION
**Pull request by sgratzl**
image

...

image

### CODE REVIEW

**Comment by tildechris** [comment]
This is great Sam!  Only one comment, in the smallest responsive view, the pictures are too big and they should be two or three across as per the current spec.  

Can you take a look?

**Comment by sgratzl** [comment]
https://github.com/cmu-delphi/www-main/blob/e39237cd4f747a5d907c16209de448a5bd08a1a8/themes/delphi/assets/css/main.scss#L8 defines that the smallest breakpoint setting. below this setting it is 1:1

**Comment by sgratzl** [comment]
> This is great Sam! Only one comment, in the smallest responsive view, the pictures are too big and they should be two or three across as per the current spec.

should be fixed

**Review by tildechris — APPROVED** [review]
Responsive version looks good.  LGTM.

**Pull request merged**
