### PR TITLE
fix: improve webp conversion

### LINKED ISSUE #367: pixelated blog preview pictures
seems like the hugo automatic webp conversion generates some weird artifacts

### PR DESCRIPTION
**Pull request by sgratzl**
closes #367 

improves the webp generation

### CODE REVIEW

**Comment by krivard** [comment]
tagging Ryan, since I've been looking at this for too long and can't tell the difference any more 😕

**Comment by ryantibs** [comment]
Still looks the same as before (thumbnails are just as blurry) to me.  E.g., first one: screenshot of thumbnail.  Second one: screenshot of full pic.

Screen Shot 2021-06-07 at 3 30 12 PM

Screen Shot 2021-06-07 at 3 32 19 PM

This is not a big deal, so if it isn't easily fixable without a lot of cycles, I'd say don't worry about it!

**Comment by sgratzl** [comment]
I just changed the thumbnails to have a higher resolution that better fits the layout. So far the had a height of 200 pixels but most of them were rendered with a height of 300px causing upscaling artifacts. Now the thumbnails have a size of 300x300 pixels which should work better in both desktop and mobile layouts

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
