### PR TITLE
make the style of the blog list the same as research paper

### PR DESCRIPTION
**Pull request by sgratzl**
image

### CODE REVIEW

**Comment by tildechris** [comment]
I like the consistency in styles, but I think we need to make tweaks to the responsive widths.  Perhaps add a medium point?  There are some min-width issues:

image

**Comment by Letsgohyde** [comment]
1. Set text to truncate after 2 lines: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=726%3A29461

**Comment by Letsgohyde** [comment]
for v2 we'll set body copy limits and reduce the summary text. LGTM for this iteration.

**Comment by sgratzl** [comment]
truncated the text to around 150 characters, see also https://gohugo.io/functions/truncate/

**Comment by sgratzl** [comment]
> truncated the text to around 150 characters, see also https://gohugo.io/functions/truncate/

image

closes #74

**Review by tildechris — APPROVED** [review]
LGTM.

**Pull request merged**
