### PR TITLE
Add Nov 2021 New York Times article to news page

### LINKED ISSUE #519: Update news page
Add Nov. 22, 2021, New York Times article featuring quotes from Roni:
- Title: Inside the C.D.C.’s Pandemic ‘Weather Service’
- Link: https://www.nytimes.com/2021/11/22/magazine/cdc-pandemic-prediction.html

### PR DESCRIPTION
**Pull request by christymelucci**
Fixes #519

### CODE REVIEW

**Comment by christymelucci** [comment]
@ryantibs or @RoniRos Please review this Draft PR

**Comment by ryantibs** [comment]
The news item looks good to me!

One very minor thought about the thumbnails used on the front page news wheel: the "D" logo looks a little plain, especially as it does when it gets used twice in visible set of three. (Screenshot below):

Screen Shot 2021-12-06 at 10 54 09 AM

Maybe we can get into a habit of using a screenshot of a graphic in the news article as its thumbnail?  

This is **not** a blocker for me to merge this PR, so I'm just going to go and already approve it, but if it's easy enough to try then feel free to give it a shot.

**Review by ryantibs — APPROVED** [review]

**Comment by christymelucci** [comment]
@krivard,
- I am looking at Ryan's request to add an image to a **news card** in the **Latest News** section at the bottom of  the **home page**.
- After reviewing **[this page](https://github.com/cmu-delphi/www-main/blob/dev/themes/delphi/layouts/partials/landing/latest-news.html)**, I am not certain if his request can be fulfilled in the current configuration as it appears that the **latest-news-item** card always/only looks for the the "D" logo [/images/placeholder-thumb.jpg](https://github.com/cmu-delphi/www-main/blob/dev/assets/images/placeholder-thumb.jpg) (although this is not the case for the  **latest-blog** card).
- Can you confirm if it is correct that an alternate image cannot be added at the moment? If so, is it a feature that is simple to add?

**Comment by krivard** [comment]
@christymelucci that is correct -- we don't currently use thumbnails for news items. Adding thumbnails for news items could be pursued at a couple different levels of complexity, but they're all out of scope for this PR. I'll write up an Issue with the details.

**Comment by christymelucci** [comment]
Merging "as is" to ensure timely post. Image improvements for news articles to be addressed shortly.

**Pull request merged**
