### PR TITLE
cmelucci/research-page-update

### PR DESCRIPTION
**Pull request by christymelucci**
Add Elena Tuzhilina's paper

### CODE REVIEW

**Review by krivard — COMMENTED** [review]
It looks like there's a banner image here; did you mean to also add this paper to the [carousel](https://github.com/cmu-delphi/www-main/blob/dev/content/_index.md?plain=1)?

**Comment by christinamelucci** [comment]
Ryan did not ask to add the paper to the carousel. I meant to have it ready incase it was needed in the future. I see now though that I should have placed it [here](https://github.com/cmu-delphi/www-main/tree/dev/assets/images/landing-page/hero-images):

**Comment by ryantibs** [comment]
Sorry for silence. I'm good with whatever images you guys choose!

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
