### PR TITLE
feat: update covidcast landing page

### LINKED ISSUE #271: update COVIDcast landing image and social preview image
since with the new design it has been outdated.

what about a picture of our new hex grid map?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #271

image

### CODE REVIEW

**Comment by tildechris** [comment]
Looks good, but can you move you move this to the first index?  I'd like it be the first thing that we highlight on the front page.

**Comment by sgratzl** [comment]
> Looks good, but can you move you move this to the first index? I'd like it be the first thing that we highlight on the front page.

so order:
 1. covidcast
 2. forecast eval
 3. survey dashboard
 4. paper 1
 5. paper 2
?

**Comment by sgratzl** [comment]
done

**Review by tildechris — APPROVED** [review]
LGTM.

**Pull request merged**
