### PR TITLE
Remove logos

### LINKED ISSUE #104: Unlogoify collaborators list
For some collaborators, we do not have permission to use their logo.  Let's convert this into one flat list.

The Google.org (no logo) entry must contain the words "With grant support from".

### PR DESCRIPTION
**Pull request by tildechris**
Fixes #104.

We lack rights to use some collaborator logos, so remove all of them.

### CODE REVIEW

**Review by sgratzl — COMMENTED** [review]
can you remove things we don't need anymore
 * images
 * collaborator-img.html partial
 * unused CSS for about-collaborators-list and similar

**Comment by tildechris** [comment]
> can you remove things we don't need anymore

Yep.

**Comment by sgratzl** [comment]
taking a look at https://delphi.cmu.edu/

image

should we keep the links?

**Comment by tildechris** [comment]
> should we keep the links?

I thought about this but I didn't have updated links for all of the partners.  Let's punt on this.

**Review by sgratzl — APPROVED** [review]
👍

**Pull request merged**
