### PR TITLE
Blog post on causal inference

### PR DESCRIPTION
**Pull request by capnrefsmmat**
Figures not added and rendering not checked. Not nearly ready to be merged; I'm using the PR so I can get previews.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Preview is looking good: it has the hero image, summary is set up, everything looks good.

I think this is ready for publication whenever @bweaver-work and @tildechris are ready to deploy it; we'd just want to update the `date` in the metadata and then deploy.

**Comment by bweaver-work** [comment]
The thumbnail is not great in the way it displays my crop. If we should create a different one, let me know and I'll crop it, but it's not a deal breaker. Otherwise looks good to me.

**Comment by tildechris** [comment]
@bweaver-work yeah, can you re-crop the thumb with it centered on the woman?  The default desktop thumb crops her out entirely:

image

**Comment by bweaver-work** [comment]
two new images uploaded

**Comment by tildechris** [comment]
Thanks @bweaver-work that looks much better.

**Review by tildechris — APPROVED** [review]
I'm not going to be a big help on reviewing the blog copy in detail, but it reads well, and technically this looks OK.

LGTM.

**Comment by capnrefsmmat** [comment]
How should we go about scheduling this? I assume it takes a full site deploy, so we'd want to pick the date for the next deploy, and on that date

* change the blog post date to that day
* ensure the HTML is rebuilt accordingly
* merge to dev
* deploy

I think we have 3 posts coming up, including this one, and this is the first one completed. Not sure which of the other two will be ready first. We could release this one with the deploy today and then other two in the following two weeks?

**Pull request merged**
