### PR TITLE
prepare for correlation page

### PR DESCRIPTION
**Pull request by sgratzl**
adds a new page and menu entry for https://github.com/cmu-delphi/www-covidcast/pull/878

### CODE REVIEW

**Comment by krivard** [comment]
"Explore correlations" appears in the menu, but clicking it brings you to the overview page instead. is that intentional?

**Comment by sgratzl** [comment]
the correlation isn't part of the COVDIcast yet. Thus, for now it falls back to its default mode. Once we merge https://github.com/cmu-delphi/www-covidcast/pull/878 and release it, it should show the correct mode

**Review by krivard — APPROVED** [review]
👍

**Comment by krivard** [comment]
(waiting to merge until cmu-delphi/www-covidcast#878 is ready, just in case we want to sneak something else out before then)

**Review by chinandrew — APPROVED** [review]
:shipit: :shipit: :shipit:

**Pull request merged**
