### PR TITLE
feat: add covidcast data alert

### PR DESCRIPTION
**Pull request by sgratzl**
adds a data alert:

image

TODO: 
 * is this the text we want?

### CODE REVIEW

**Comment by tildechris** [comment]
I like the style, but can we change the text to:

"Due to an issue with our backend, no data newer than February 1st is being added to the system.  It will take us about a week to address the issue and resume daily updates."

**Comment by sgratzl** [comment]
> "Due to an issue with our backend, no data newer than February 1st is being added to the system. It will take us about a week to address the issue and resume daily updates."

**Comment by krivard** [comment]
A week since Feb 1st has already happened. Maybe 

"We expect to resume daily updates or provide a new estimate by February 15th"

**Comment by tildechris** [comment]
Updated text as per Katie.

image

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
