### PR TITLE
generate and show Table of Content in blog pages

### LINKED ISSUE #92: Consider adding a table-of-contents for blog posts
With a new line-width, there is a lot of white space in the blog posts.  The line-width also makes the posts longer to scroll through.

We should investigate adding a TOC to make navigation easier.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #92 

toc

### CODE REVIEW

**Comment by tildechris** [comment]
This is amazing.  Only one problem is that the TOC overflows the blog content at the bottom of the page:

image

**Comment by tildechris** [comment]
Sam, if we can fix that overflow issue I think we can pull this into the redesign.  Thoughts?

**Comment by sgratzl** [comment]
was easier than expected to fix: https://getuikit.com/docs/sticky#bottom

**Review by tildechris — APPROVED** [review]
Thanks Sam, this works great.  LGTM.

**Pull request merged**
