### PR TITLE
C2b blogpost minor typos fix

### PR DESCRIPTION
**Pull request by Ananya-Joshi**
-Reduces preview on Blog page to be within word limit
-Minor typos fix

### CODE REVIEW

**Comment by sgratzl** [comment]
@Ananya-Joshi can you resolve the merge conflict, please

**Comment by Ananya-Joshi** [comment]
Is there anything else left to complete here?

**Review by sgratzl — APPROVED** [review]
👍

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
