### PR TITLE
npm + covidcast

### PR DESCRIPTION
**Pull request by sgratzl**
based on #37 

uses https://github.com/cmu-delphi/www-covidcast/pull/631 to add covidcast as a dependency and include its assets

### CODE REVIEW

**Comment by tildechris** [comment]
It looks like the netlify build is broken:

image

I ran a local build and this looks like a good solution so far.

**Comment by sgratzl** [comment]
git dependencies aren't that much fun, but it works: 

https://deploy-preview-38--cmu-delphi-main.netlify.app/covidcast/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201112&signalType=value&encoding=color&mode=timelapse&region=42003

**Review by tildechris — APPROVED** [review]
LGTM, thanks Sam.  This is a solid improvement.

**Comment by sgratzl** [comment]
won't merge tho, till we decide which version (uikit vs original style) in covidcast

**Comment by sgratzl** [comment]
closing in favor of #43

**Pull request closed without merging**
