### PR TITLE
switch to Arial svg font

### LINKED ISSUE #110: Blog figures should use the correct font.
In the migration to hugo, the figures in the blogs are using an incorrect font.  For an example see: https://github.com/cmu-delphi/www-main/pull/107#issuecomment-733200886

Fix to use the originally intended font.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #110 

by using the `mscorefonts` anaconda package

before (on my machine)

image

after: (on my machine)

image

### CODE REVIEW

**Review by tildechris — COMMENTED** [review]
This looks good on desktop and mobile.  Question - how does one configure which font the svgs use?  Will it just default to Arial in the future or do blog authors have to specify?

**Comment by sgratzl** [comment]
I haven't found a way to proper configure/specify with font to use, R seems to use https://www.rdocumentation.org/packages/gdtools/versions/0.1.1/topics/match_family to determine which font family to use depending on availability. The `mscorefonts` ensures that `Arial` is available.

**Comment by tildechris** [comment]
So in this case, you've made sure that Arial is available and when you regenerated the svgs, `match_family` decided that Arial is a better choice than Dejavu sans?

**Comment by sgratzl** [comment]
The problem is that there are several layers on top of each other, blogdown -> R -> svglite device and I don't know a way to specify options for the lowest one. It seems like Arial is the default sans font (see also https://svglite.r-lib.org/articles/fonts.html). It wasn't used before since in a docker environment there are no fonts at all installed by default. The Anaconda environment ensures that we have the Arial font now.

**Review by tildechris — APPROVED** [review]
Thanks for the background.  LGTM.

**Pull request merged**
