### PR TITLE
add causal post images

### PR DESCRIPTION
**Pull request by bweaver-work**

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Looks good to me. @tildechris Are we okay using just WebP, or do we use JPEG, or both, or...?

**Comment by bweaver-work** [comment]
Added jpg version of images per conversation with @tildechris

**Comment by capnrefsmmat** [comment]
Thanks; I think I'll manually merge this into the blog post's branch so I can then add it to the post and rebuild the preview

**Comment by capnrefsmmat** [comment]
Done; I'll close this, since it's now in the other PR

**Pull request closed without merging**
