### PR TITLE
feat: full screen popup for blog images

### PR DESCRIPTION
**Pull request by sgratzl**
injects a full screen button to blog images:

image

image

### CODE REVIEW

**Comment by tildechris** [comment]
This is exactly what I was looking for.  There's one possibly unrelated-to-this-change item, but it looks like the aspect ratio of the figures is off in some circumstances.  I wonder if this is because that we're using SVG directly?  Is there a way to maintain the original aspect ratio and still have this full-screen behavior?

**Comment by sgratzl** [comment]
> This is exactly what I was looking for. There's one possibly unrelated-to-this-change item, but it looks like the aspect ratio of the figures is off in some circumstances. I wonder if this is because that we're using SVG directly? Is there a way to maintain the original aspect ratio and still have this full-screen behavior?

can you post an example, please

**Comment by tildechris** [comment]
Redesign: 
image

Existing version: 
image

Maybe it's that the font changed, but the redesign feels stretched out.

**Comment by sgratzl** [comment]
yes, I assume it is a font difference. While generating the images it specifies that it should use `font-family: DejaVu Sans;`. However, I have no idea how to tell R to use a different font and reliable make sure that this font is available everywhere.

**Comment by tildechris** [comment]
Ok, I'll open a bug and we'll solve this in v2.

**Review by tildechris — APPROVED** [review]
LGTM.

**Pull request merged**
