### PR TITLE
center of excellence page

### PR DESCRIPTION
**Pull request by sgratzl**
adds a simple center of excellence page:

https://deploy-preview-292--cmu-delphi-main.netlify.app/about/center-of-excellence/

deploy-preview-292--cmu-delphi-main netlify app_about_center-of-excellence_

### CODE REVIEW

**Comment by RoniRos** [comment]
Thanks @sgratzl !   
I'm sorry but I just noticed one text issue:
In the very last line of the page, we should use the full name of the CDC, which is:
U.S. Centers for Disease Control and Prevention (US CDC)

Please note the plural form ("Centers").
We prepend "U.S." because nawadays there are others, e.g. E-CDC in Europe, Chinese CDC, and others.

**Comment by sgratzl** [comment]
> Thanks @sgratzl !
> I'm sorry but I just noticed one text issue:
> In the very last line of the page, we should use the full name of the CDC, which is:
> U.S. Centers for Disease Control and Prevention (US CDC)
> 
> Please note the plural form ("Centers").
> We prepend "U.S." because nowadays there are others, e.g. E-CDC in Europe, Chinese CDC, and others.

image

**Comment by Letsgohyde** [comment]
LGTM :)

Thanks @sgratzl

**Comment by chinandrew** [comment]
Is the extra whitespace between "for" and "Disease"  so the left and right edges are justified?
Screenshot from 2021-04-20 09-40-49

**Comment by sgratzl** [comment]
> Is the extra whitespace between "for" and "Disease" so the left and right edges are justified?

I didn't create this image but just used the one from a a previous website version. But I guess that was the motivation

**Review by chinandrew — APPROVED** [review]
:shipit: :shipit: :shipit:

**Pull request merged**
