### PR TITLE
add prettier and format code

### PR DESCRIPTION
**Pull request by sgratzl**
installs and formats all files using https://prettier.io

### CODE REVIEW

**Comment by tildechris** [comment]
This is a good infrastructure upgrade, but it's a large change.  Are there drawbacks to deferring this to v2?

Also, for all of the blog html, isn't that generated?

**Comment by sgratzl** [comment]
> This is a good infrastructure upgrade, but it's a large change. Are there drawbacks to deferring this to v2?

no that's why I added the v2 milestone



> Also, for all of the blog html, isn't that generated?

the HTML changes are just because of some front matter change

**Comment by tildechris** [comment]
> no that's why I added the v2 milestone

Noted.  We can merge this after we make the RC.

**Review by tildechris — APPROVED** [review]
LGTM, you can merge when you finish.  This is hard to review with all of the formatting changes, but if there are any issues, we fix them in follow-up PRs.

**Pull request merged**
