### PR TITLE
Vaccine uptake/acceptance/hesitancy among Hispanic adults

### PR DESCRIPTION
**Pull request by capnrefsmmat**
Draft blog post; submitting PR so I can preview it and tweak as needed.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
@sgratzl I don't think I have software to generate a WebP version of the thumbnail image for the post, and when I put in a JPG with the dimensions Chris told me long ago, the sizing comes out wrong:

Screen Shot 2021-04-27 at 4 27 56 PM

Any idea what I'm doing wrong here?

**Comment by sgratzl** [comment]
> Any idea what I'm doing wrong here?

fixed

and I also added the webp version

**Comment by sgratzl** [comment]
@capnrefsmmat I changed this PR to be a draft, please mark it as ready once it is ready to be merged

**Comment by capnrefsmmat** [comment]
Just updated the date and summary, and I think this is ready to go.

**Review by sgratzl — APPROVED** [review]
👍 from a technical view

**Review by krivard — APPROVED** [review]
Several of the figures are illegible inline, but given the full-screen option, that's acceptable to me

**Pull request merged**
