### PR TITLE
menu changes and CMU logo

### PR DESCRIPTION
**Pull request by sgratzl**
add the cmu wordmark to the header and footer (footer is just a draft). Moreover, i changed the header logic and structure such that we have three different modes: desktop, hybrid (when the main menu will get cut off), and mobile: 

header: 
image

header mobile:

image

header hybrid:
image

footer: (to be refined)

image

@Letsgohyde the easiest if you have small style changes (like margins,..) when you change them directly in this branch or we can do it together.

### CODE REVIEW

**Comment by tildechris** [comment]
Looks good Sam!  A few comments:

* The footer should be the full unit mark.  If we show CMU in the mobile nav, we need to have Carnegie Mellon University somewhere on the same page.
* Can you also change the site title to "DELPHI" instead of "The Delphi Team"?

**Comment by sgratzl** [comment]
> * The footer should be the full unit mark.  If we show CMU in the mobile nav, we need to have Carnegie Mellon University somewhere on the same page.

image

image

image


> 
> * Can you also change the site title to "DELPHI" instead of "The Delphi Team"?

done

**Review by tildechris — APPROVED** [review]
LGTM.

**Comment by Letsgohyde** [comment]
Thanks @sgratzl - this LGTM - I have some alignment notes, but we can work on that together per your notes above :)

**Pull request merged**
