### PR TITLE
cmelucci/team-page-update

### PR DESCRIPTION
**Pull request by christymelucci**
Move Joseph Greene from Core Members to Past Members

Add 2 Contributors:
- Chloe You, University of University of British Columbia
- Ken Mawer, University of University of British Columbia

### CODE REVIEW

**Review by krivard — COMMENTED** [review]
There's a photo of Maggie but not a listing in index.md -- is that intended?

**Review by krivard — APPROVED** [review]
👍

**Comment by christymelucci** [comment]
Converted to draft. Need to add Joe's dates.

**Comment by christymelucci** [comment]
@krivard Added Joe's dates. OK to merge?

**Comment by krivard** [comment]
all set!

**Pull request merged**
