### PR TITLE
style: covidcast app full height

### PR DESCRIPTION
**Pull request by sgratzl**
assigns 100vh to the navigation + covidcast:

image

However, this will create a scrollbar on the right side to access the footer which can interfere with mouse wheel zoom in the map.

### CODE REVIEW

**Comment by tildechris** [comment]
This is an improvement.  I wonder, however, if we really need to include the footer on the main covidcast page.  @Letsgohyde thoughts?

**Comment by sgratzl** [comment]
remove the footer for testing

**Comment by tildechris** [comment]
Reviewed with the team: we are going to remove the footer from the "map" page and assume that the visualization is a SPA and should take 100% of height with no scrollbar.

**Review by tildechris — APPROVED** [review]
LGTM.  Thanks Sam.

**Pull request merged**
