### PR TITLE
Redesign Release

### PR DESCRIPTION
**Pull request by tildechris**
This is the release for the large delphi.cmu.edu redesign.

### CODE REVIEW

**Comment by tildechris** [comment]
> we could consider directly linking to https://github.com/cmu-delphi/www-covidcast/releases/download/v1.11.0/www-covidcast-1.11.0.tgz which will speed up the built since covidcast is already built

Good idea.  What's the syntax like for that in package.json?

**Comment by sgratzl** [comment]
> Good idea. What's the syntax like for that in package.json?

just put in the URL as "version" similar to the `github:...` one

**Comment by sgratzl** [comment]
we might wanna merge the changes from https://github.com/cmu-delphi/www-main/pull/121 which fixes some small stuff

**Comment by tildechris** [comment]
I cherry picked these changes.  Please take a look.

**Review by sgratzl — APPROVED** [review]

**Pull request merged**
