### PR TITLE
Add Richard Zhuang and Ryan Nayebi to Team Page

### PR DESCRIPTION
**Pull request by christymelucci**
-Add Richard Zhuang and Ryan Nayebi, UC Berkeley, to Contributors on Team Page (2024 summer interns working with Dmitry Shemetov)

### CODE REVIEW

**Review by melange396 — APPROVED** [review]
Looks good!  Do you wanna put a note on them like we have done for other summer interns?  Or wait til the summer is over for that?

https://github.com/cmu-delphi/www-main/blob/a9390df0569e22ed6a7e4d9b4433fbd9f69bf1b9/content/people/index.md?plain=1#L43

**Comment by christymelucci** [comment]
@melange396 In the past, we waited until the member left Delphi to add reference to summer intership, etc. Please do feel free to  add this info now if you think it makes sense and / or would be useful.

**Comment by melange396** [comment]
I'm fine with either way ¯\\\_(ツ)_/¯

**Comment by christymelucci** [comment]
Let's use the approach that was used in the past. We can add the internship info later.

**Pull request merged**
