### PR TITLE
style: adapt new single blog style

### PR DESCRIPTION
**Pull request by sgratzl**
sticking out images / code

image

image

### CODE REVIEW

**Comment by tildechris** [comment]
Hmm... I like that it's bigger, but it now feels out of balance.  The floating TOC prevents us from moving the image margin out to the left too much.

For comparison see: https://covidtracking.com/blog/north-dakota-deaths-backlog

There's equal margins for figures on both sides of the main body.  Do you have any thoughts on how to incorporate a balanced layout while retaining the TOC?

**Comment by sgratzl** [comment]
bringing @jennyxxdance and @Letsgohyde into the loop since the changes are based on their Figma sketches

**Comment by Letsgohyde** [comment]
Thanks for sharing this update @sgratzl - I think the TOC has a lot of value so that right leaning images is ok, however there are charts that seem to have a lot of left margin, can we center align the charts within the center columns? In the attached example you'll see the chart above that I've moved over and the bottom chart (default position) is not center aligned. 

image

**Comment by Letsgohyde** [comment]
That said, Center align smaller charts and allow larger charts to expand to the col rightward of center. 
Example of where content should be expanded beyond the center col. 
image
image

**Comment by sgratzl** [comment]
I added a flag to the blog posts which allows to create "wide" figures. The result looks like:

regular: 

image

wide:
image

**Review by tildechris — APPROVED** [review]
LGTM.  Thanks for the feedback @Letsgohyde.  @sgratzl this flows nicely and I like how the author can choose to show wide figures or not.

**Pull request merged**
